language: python
python:
- 3.5.2
- '3.6'
install:
- pip install .
script: nosetests
deploy:
  provider: pypi
  user: khillion
  password:
    secure: EgZ17iFM6JjDePsvBk+p4OidU7RYKDD0+UynRJ2uz3dQuFNJZGscOAm5/BF5xmLud5kNn8lUNIyAIs5oI+zeS05Ycuu+Izl+loQy9oPhGe7o1FRWkE3A3sz2UcHsm0wxgBqYw0eX3b+u3jKZ4fKNASbjLdTFNphHoFV/pC/nEvRKkBh0tdE6/8eKc0GIxlCBkWHPAbg6gnPXczV6+1ATjTBObVjAbAjwvSwE6m3WDKXwg5hYx08TOF2smmh/6xljvtBeKHQGtvY9QfNCj50/GPJc2Hlms1hrPYbD+XA4lJeCvqI/x4kQNVVgNHnUW8og7L2OaCCLBPxB8ZW6QK9sYP37WizANEvEd1h8o3aFuswMrP9mN6acpaiMbYosDam1QP6JMNa7CAmR7qIm5d7bEEys7xK5kRrXKXLO1uiKlYIRXsVq5VmIFlWB1w+TeSf42vSebkSOfjuoUdYHbOGOy0uagsQFLaj0YkMTFdABq98VCJGwAceh4mitPD3DBFbt0scpSHTpQvSoYgQxMX8pn5ja3VMk0oR/fa4JnXo4C+iEkX8251jyE0BbL+va70Ozz/kOm3ygIhd7Y5eRGtVFO2RZUMbHhsisqKwU/I57pL6ndaDFjceeUcjZ75u3ztBGN4M+uaXCtf/bCVMN5eceYWr6GKaSkhkCnNW/+7tY/KE=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: C3BI-pasteur-fr/Salmonella-CRISPR-Typing
